services:
  db:
    image: postgres:15
    container_name: timesink-db
    restart: always
    environment:
      POSTGRES_USER: timesink
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: timesink
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: timesink-backend
    depends_on:
      - db
    env_file:
      - .env.prod
    networks:
      - app_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: timesink-frontend
    depends_on:
      - backend
    networks:
      - app_net

  nginx:
    image: nginx/alpine
    container_name: timesink-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
