services:
  db:
    image: postgres:15
    container_name: timesink-db
    restart: always
    environment:
      POSTGRES_USER: timesink
      POSTGRES_PASSWORD: timesink
      POSTGRES_DB: timesink
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: timesink-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://timesink:timesink@db:5432/timesink
      NODE_ENV: production
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: timesink-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
