FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package*.json ./frontend/
RUN npm ci --omit=dev

COPY frontend ./frontend
RUN npm run build --workspace=frontend

FROM nginx:alpine AS runner
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]